/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e2_tp5;

import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.lang.System.exit;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Luciano
 */
public class Formulario extends javax.swing.JFrame implements ActionListener {
    
    JLabel nombre = new JLabel("Nombre:");
    JTextField cnombre=new JTextField("");
    JLabel dni = new JLabel("DNI:");
    JTextField cdni=new JTextField("");
    JLabel domicilio = new JLabel("Domicilio:");
    JTextField cdomicilio=new JTextField("");
    JLabel tel = new JLabel("Telefono:");
    JTextField ctel=new JTextField("");
    
    JButton ace=new JButton("Aceptar");
    JButton can=new JButton("Cancelar");
    
   // E2_tp5 f = new E2_tp5();
    
    /**
     * Creates new form Formulario
     */
    public Formulario() {
        super("Cargar Datos Cliente");
        this.setBounds(300, 150, 320, 450);
        
        JPanel panel = new JPanel();
        panel.setLayout(new GridLayout(4,1));
        panel.add(nombre);
        panel.add(cnombre);
        panel.add(dni);
        panel.add(cdni);
        panel.add(domicilio);
        panel.add(cdomicilio);
        panel.add(tel);
        panel.add(ctel);
        
        JPanel panel2=new JPanel();
        panel2.setLayout(new GridLayout(1,2));
        panel2.add(ace);
        panel2.add(can);
        
        ace.addActionListener(this);
        can.addActionListener(this);
        
         FlowLayout fl=new FlowLayout(1,40,50);
        this.setLayout(fl);
        add(panel);
        add(panel2);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
         try{
                Object op = ae.getSource();
                
                if(op==ace){
                    String nomb, dom;
                    Integer dni2, telef;
                
                    nomb = cnombre.getText();
                    dom = cdomicilio.getText();
                    dni2 = Integer.parseInt(cdni.getText().trim());
                    telef = Integer.parseInt(ctel.getText().trim());
                    
                    setVisible(false);
                    MostrarDatos mostrar = new MostrarDatos(nomb,dni2,dom,telef);
                    mostrar.setVisible(true);
                    
                    
                    
                }else if(op==can){
                    System.exit(0);
                }
                
            }catch(Exception exc) {
            System.out.println(exc);
                                    }

      }

    }

