/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e2_tp5;

import java.awt.FlowLayout;
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Luciano
 */
public class MostrarDatos extends javax.swing.JFrame {

    /**
     * Creates new form MostrarDatos
     */
    private String nombre;
    private int dni;
    private String domicilio;
    private int tel;
    JLabel labelnombre = new JLabel("Nombre:");
    JLabel lnombre =new JLabel();
    JLabel labeldni = new JLabel("DNI:");
    JLabel ldni=new JLabel();
    JLabel labeldomicilio = new JLabel("Domicilio:");
    JLabel ldomicilio=new JLabel();
    JLabel labeltel = new JLabel("Telefono:");
    JLabel ltel=new JLabel();
    
    public MostrarDatos(String nombre, int dni, String domicilio, int tel) {
        super("Mostrar Datos Cliente");
        initComponents();
    this.nombre=nombre;
    this.dni=dni;
    this.domicilio=domicilio;
    this.tel=tel;
    
    lnombre.setText(nombre);
    ldni.setText(Integer.toString(dni).trim());
    ldomicilio.setText(domicilio);
    ltel.setText(Integer.toString(tel).trim());
    
        this.setBounds(300, 150, 320, 450);
        
        JPanel panel = new JPanel();
        panel.setLayout(new GridLayout(4,1));
        panel.add(labelnombre);
        panel.add(lnombre);
        panel.add(labeldni);
        panel.add(ldni);
        panel.add(labeldomicilio);
        panel.add(ldomicilio);
        panel.add(labeltel);
        panel.add(ltel);
    
        FlowLayout fl=new FlowLayout(1,40,50);
        this.setLayout(fl);
        add(panel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
