/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesGraficas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import trabajodelaboratorio.Empleado;
import trabajodelaboratorio.Jefe;

/**
 *
 * @author Luciano
 */
public class ListadoJefes extends javax.swing.JPanel {

    /**
     * Creates new form ListadoJefes
     */
    javax.swing.JPanel panel;
    javax.swing.JFrame ventana;
    ArrayList<Jefe> arrayJefes;
    public ListadoJefes(javax.swing.JPanel panel, javax.swing.JFrame ventana) {
        initComponents();
    
        this.panel=panel;
        this.ventana=ventana;
        arrayJefes = new ArrayList<>();
        
        /* Acceso al array empleados para crear uno nuevo solo con los jefes*/
        ArrayList<Empleado> lista = VentanaPrincipal.empleados;
        for (int i = 0; i < lista.size(); i++) {
            if(lista.get(i) instanceof Jefe)
                arrayJefes.add((Jefe)lista.get(i));
        }
        
        /* Creacion de la tabla con los jefes*/
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        Object[] fila = new Object[tableModel.getColumnCount()];
        for (int i = 0; i < arrayJefes.size(); i++) {
            {
            fila[0] = arrayJefes.get(i).getNroLegajo();
            fila[1] = arrayJefes.get(i).getNombre();
            fila[2] = arrayJefes.get(i).getApellido();
            fila[3] = arrayJefes.get(i).getArea();
            tableModel.addRow(fila);
            }
         }
         jTable1.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° Legajo", "Nombre", "Apellido", "Ingreso"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Ver Empleados a Cargo");
        jButton1.setToolTipText("Lista de Empleados a cargo del Jefe Seleccionado");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Menu Principal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Jefes de Área");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        ventana.setContentPane(panel);
        panel.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
    if(jTable1.getSelectedRow()==-1){
        JOptionPane.showMessageDialog(this, "Debe seleccionar una opcion");
        return;
    }   
     int indice=jTable1.getSelectedRow();
        
     this.setVisible(false);
     ListadoEmpleadosAcargo panelSig = new ListadoEmpleadosAcargo(arrayJefes,indice,this,ventana);
     ventana.setContentPane(panelSig);
     panelSig.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
