/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesGraficas;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import trabajodelaboratorio.Conyuge;
import trabajodelaboratorio.Empleado;
import trabajodelaboratorio.Familiar;
import trabajodelaboratorio.Hijo;

/**
 *
 * @author Luciano
 */
public class ListadoFamiliares extends javax.swing.JPanel {

    /**
     * Creates new form ListadoFamiliares
     */
    javax.swing.JPanel panel;
    javax.swing.JFrame ventana;
    int indice;
    public ListadoFamiliares(javax.swing.JPanel panel,javax.swing.JFrame ventana,int indice) {
        initComponents();
        
        this.panel=panel;
        this.ventana=ventana;
        this.indice=indice;
        
        ArrayList empleados= new ArrayList();
        VentanaPrincipal vp=(VentanaPrincipal)ventana;
        empleados=vp.getEmpleados();
        Empleado emp=(Empleado)empleados.get(indice);
        
                
     DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
     ArrayList<Familiar> lista = emp.getFamiliares();
     Object[] fila = new Object[tableModel.getColumnCount()];
        for (int i = 0; i < lista.size(); i++) {
             if(lista.get(i) instanceof Conyuge){
                 Conyuge con=(Conyuge)lista.get(i);
                 
            fila[0] = con.getNombre();
            fila[1] = con.getApellido();
            fila[2] = ("Conyuge");
            fila[3] = con.getDni();
            tableModel.addRow(fila);
            }
             else{
                  Hijo hijo=(Hijo)lista.get(i);
            fila[0] = hijo.getNombre();
            fila[1] = hijo.getApellido();
            
                char a= hijo.getSexo();
                if(a=='M'){
                fila[2] = ("Hijo");}
                else{
                fila[2] = ("Hija");} 
                
            fila[3] = hijo.getDni();
            tableModel.addRow(fila);
             }
     }
     jTable1.setModel(tableModel);
        
     jLabel2.setText(emp.getNombre()+" "+emp.getApellido()+" (N°Legajo:"+emp.getNroLegajo()+")");
    }

        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Parentesco", "Documento", "Fec. de Nacimiento"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Volver");
        jButton1.setToolTipText("Regresar al Listado de Empleados");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Familiares a cargo de:");

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)
                        .addGap(0, 141, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        ventana.setContentPane(panel);
        panel.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
